spring.application.name=BeSuffle

spotify.client-id=${SPOTIFY_CLIENT_ID:}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET:}

# Configurações do banco de dados

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dailyalbum
spring.datasource.username=postgres
spring.datasource.password=Senhalol.123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true